version: "3.5"
services:
  polkadot:
    build:
      context: ./polkadot
      args:
        UPSTREAM_VERSION: v0.9.42
    image: "polkadot.polkadot.dnp.dappnode.eth:0.1.0"
    restart: unless-stopped
volumes:
  polkadot-data: {}
